### ISSUE TITLE
"errorMessage": "Cannot assign to read only property - Error

### ISSUE THREAD

**Issue by user1342** [alexa/skill-sample-nodejs-trivia#14] opened 2017-05-26 15:14 UTC
Hello everyone. I was wondering if anyone had come across this error. Sporadically I am receiving this error when testing the Lambda function. This was occurring far more regularly after I changed the questions however after switching back the problem still persists, if less often. There doesn't appear to be a pattern behind why the error occurs.

> {
  "errorMessage": "Cannot assign to read only property '74' of string 'QUESTIONS.1.The 1964 classic Rudolph The Red Nosed Reindeer was filmed in. '",
  "errorType": "TypeError",
  "stackTrace": [
    "populateRoundAnswers (/var/task/index.js:340:28)",
    "Object.StartGame (/var/task/index.js:126:28)",
    "emitOne (events.js:96:13)",
    "AlexaRequestEmitter.emit (events.js:188:7)",
    "AlexaRequestEmitter.EmitWithState (/var/task/node_modules/alexa-sdk/lib/alexa.js:408:15)",
    "Object.LaunchRequest (/var/task/index.js:101:14)",
    "emitNone (events.js:86:13)",
    "AlexaRequestEmitter.emit (events.js:185:7)",
    "AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:197:10)",
    "AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:161:23)"
  ]
}

or 

> {
>   "errorMessage": "Cannot assign to read only property '64' of string 'QUESTIONS.14.Santa only has one female reindeer. Which one is it?'",
>   "errorType": "TypeError",
>   "stackTrace": [
>     "populateRoundAnswers (/var/task/index.js:340:28)",
>     "Object.StartGame (/var/task/index.js:126:28)",
>     "emitOne (events.js:96:13)",
>     "AlexaRequestEmitter.emit (events.js:188:7)",
>     "AlexaRequestEmitter.EmitWithState (/var/task/node_modules/alexa-sdk/lib/alexa.js:408:15)",
>     "Object.LaunchRequest (/var/task/index.js:101:14)",
>     "emitNone (events.js:86:13)",
>     "AlexaRequestEmitter.emit (events.js:185:7)",
>     "AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:197:10)",
>     "AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:161:23)"
>   ]
> }

Any help would be appreciated.
James

![image](https://cloud.githubusercontent.com/assets/28961606/26500629/6b8b8450-41eb-11e7-9362-04c03357ab3d.png)

**Comment by nyan-matt** [comment] 2017-06-13 02:00
+1

**Comment by nyan-matt** [comment] 2017-06-17 16:00
`index.js` probably needs a good scrubbing. A quick look via [JSHint](http://jshint.com/) shows a number of warnings, which throw errors in strict mode. Notably, `this` being undefined, and some vars being used out of scope. You could remove strict mode to get around the errors, but better solution would be refactor clean up. Attaching JsHint output:
```
2	It's not necessary to initialize 'APP_ID' to 'undefined'.
20	['QUESTIONS_EN_US'] is better written in dot notation.
47	['QUESTIONS_EN_US'] is better written in dot notation.
53	['QUESTIONS_EN_GB'] is better written in dot notation.
59	['QUESTIONS_DE_DE'] is better written in dot notation.
87	It's not necessary to initialize 'APP_ID' to 'undefined'.
165	['speechOutput'] is better written in dot notation.
165	['repromptText'] is better written in dot notation.
200	['speechOutput'] is better written in dot notation.
200	['repromptText'] is better written in dot notation.
204	['speechOutput'] is better written in dot notation.
204	['repromptText'] is better written in dot notation.
208	['speechOutput'] is better written in dot notation.
208	['repromptText'] is better written in dot notation.
237	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
240	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
241	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
242	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
243	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
244	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
245	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
247	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
247	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
247	['correctAnswerIndex'] is better written in dot notation.
249	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
252	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
255	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
259	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
259	['currentQuestionIndex'] is better written in dot notation.
260	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
261	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
263	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
263	Missing semicolon.
268	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
270	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
273	Missing semicolon.
276	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
277	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
279	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
289	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
289	If a strict mode function is executed using function invocation, its 'this' value will be undefined.
348	'temp' used out of scope.
350	'temp' used out of scope.
```

**Comment by michaelaflores** [comment] 2017-06-17 23:39
+1 I have the same problem.

**Comment by michaelaflores** [comment] 2017-06-18 02:09
I had also encountered this after putting in my own question and answer set. Removing strict mode alleviated the issue for me.

**Comment by mikeybyker** [comment] 2017-07-03 09:21
@user1342  - the problem you are seeing there is down to the translation/i18n library messing up the questions. 

You can see the issue if you console.log translatedQuestions:
```javascript
// index.js
var translatedQuestions = this.t("QUESTIONS");
console.log(translatedQuestions);
```
You can see that several questions get messed up - for example the 2nd question ends up as
```javascript
{ 'The 1964 classic Rudolph The Red Nosed Reindeer was filmed in.': 'QUESTIONS.1.The 1964 classic Rudolph The Red Nosed Reindeer was filmed in.' },
```
The answers array has been wiped out and replaced with that mashed up string.
If any of the randomly picked questions to ask include one of those 'broken' ones, you get those errors you are seeing.

The issue is, strangely enough, simply down to the question text having a full-stop/period - again look at the logs and notice that any question with a "."  will break the app.
This happens as i18next (the t() method) uses by default a full-stop as a delimiter - an odd choice really.

To solve this - the standard way to change the delimiter would be in the i18n init() method - but the alexa-sdk hides that from us (be good if it didn't...). So instead we have to specify the delimiter on each call to the t() method - not as handy, but in this case at least it only occurs twice -  with each call to translate the questions - in StartGame and handleUserGuess (index.js)

In both instances, (tl;dr!) change to something like:
```javascript
var translatedQuestions = this.t("QUESTIONS", {keySeparator: '#'});
```
and you should be good. Writing a method to add the keySeparator in automatically might be an idea if you find yourself using it a fair bit.

Cheers

**Comment by illgitthat** [comment] 2017-07-19 04:06
Thanks https://github.com/alexa/skill-sample-nodejs-trivia/issues/14#issuecomment-312594753 that change solved the error for me!

**Comment by coolcat-creations** [comment] 2017-10-30 09:50
thank you @mikeybyker ! that solved the issue

**Comment by akersh-s** [comment] 2018-01-18 23:41
Fixed as of PR# 56

**Closed by akersh-s** 2018-01-18 23:41 UTC
